services:

#  database:
#    restart: always
#    container_name: postgres_t1_3
#    image: 'postgres:16.1-alpine'
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER: ${POSTGRES_USERNAME}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'mrx_db'
      POSTGRES_USER: 'mrx'
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock