CREATE TABLE t_metrics
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(1000),
    date TIMESTAMP,
    name_id BIGINT REFERENCES t_metric_names (id) NOT NULL,
    base_unit_id BIGINT REFERENCES t_base_unit_names (id)
);