CREATE TABLE t_measurements
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value REAL NOT NULL,
    metric_id BIGINT REFERENCES t_metrics (id),
    statistic_id BIGINT REFERENCES t_measurement_statistic_names (id) NOT NULL
);